### ISSUE TITLE
WeatherCast del_btn error

### ISSUE THREAD

**Issue by tjoon** [kukuru/roadbook#2]
핵심 문법과 예제로 배우는 코틀린 책으로 공부중에 해결이 잘 안되는 부분이 있어 문의드립니다.
WeatherCast 앱에서 X 이미지버튼을 누르면 StackOverflowError가 발생합니다.
제가 잘못 따라쳤나 해서 프로젝트를 그대로 다운받아서 실행했는데도 이와 같은 에러가 발생합니다.

**Comment by kukuru** [comment]
안녕하세요.

StackOverflowError가 난 이유는 OnClick 함수가 여러번 불려서 그렇습니다.
소스 수정해서 Github에 올려두었습니다.
소스 다시 다운 받아 확인해보세요.

그리고 날씨 api가 조금 변경되어 이 부분도 함께 변경해주어야 합니다.
data/WeatherData.kt파일과
WeatherListViewAdapter.kt 파일 함께 확인해 주세요.

감사합니다.

2018년 6월 20일 오전 3:42, tjoon <notifications@github.com>님이 작성:

**Comment by tjoon** [comment]
소스를 다시 다운받아 확인하니 정상 작동합니다.

감사합니다.

예제 앱이 여러 있어서 개인적으로 무척 마음에 드는 책입니다.

**Comment by kukuru** [comment]
안녕하세요.

도움이 되었다니 기쁘네요 ^^
책 보시면서 궁금한점있으면 연락주세요.

감사합니다.

2018년 6월 22일 (금) 오전 1:10, tjoon <notifications@github.com>님이 작성:
